/*

 BKG_MAP_MINE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bkg_tile_mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_map_mineWidth 20
#define bkg_map_mineHeight 18
#define bkg_map_mineBank 0

extern unsigned char bkg_map_mine[];

/* End of BKG_MAP_MINE.H */
